name: formx_sdk_flutter
description: A Flutter plugin for using FormX SDK in iOS and Android applications.
version: 1.0.0
repository: https://github.com/oursky/formx_sdk_flutter

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: ai.formx.mobile.sdk.formx_sdk_flutter
        pluginClass: FormxSdkFlutterPlugin
      ios:
        pluginClass: FormxSdkFlutterPlugin

